title: myrealname
description: "A Jekyll Blog Theme For Hackers"
author:
  name: "hwang"
  email: "starrynightablue@gmail.com"
  url: "https://story.kakao.com/_GUl9C9"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
year : "2020"
